export const CHECK_BOOKING_LOADING = 'CHECK_BOOKING_LOADING';
export const CHECK_BOOKING_SUCCESS = 'CHECK_BOOKING_SUCCESS';
export const CHECK_BOOKING_FAILED = 'CHECK_BOOKING_FAILED';
export const CHECK_BOOKING_RESET = 'CHECK_BOOKING_RESET';

export const CLEAR_ERROR = 'CLEAR_ERROR';
