export const CHECK_BOOKING_LOADING = 'CHECK_BOOKING_LOADING';
export const CHECK_BOOKING_SUCCESS = 'CHECK_BOOKING_SUCCESS';
export const CHECK_BOOKING_FAILED = 'CHECK_BOOKING_FAILED';
export const CHECK_BOOKING_RESET = 'CHECK_BOOKING_RESET';

export const BOOKED_DATES_SUCCESS = 'BOOKED_DATES_SUCCESS';
export const BOOKED_DATES_FAILED = 'BOOKED_DATES_FAILED';

export const MY_BOOKINGS_SUCCESS = 'MY_BOOKINGS_SUCCESS';
export const MY_BOOKINGS_FAILED = 'MY_BOOKINGS_FAILED';

export const CLEAR_ERROR = 'CLEAR_ERROR';
