export const ALL_ROOMS_SUCCESS = 'ALL_ROOMS_SUCCESS';
export const ALL_ROOMS_FAILED = 'ALL_ROOMS_FAILED';

export const ROOM_DETAIL_SUCCESS = 'ROOM_DETAIL_SUCCESS';
export const ROOM_DETAIL_FAILED = 'ROOM_DETAIL_FAILED';

export const CREATE_REVIEW_LOADING = 'CREATE_REVIEW_LOADING';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_FAILED = 'CREATE_REVIEW_FAILED';
export const CREATE_REVIEW_RESET = 'CREATE_REVIEW_RESET';

export const REVIEW_AVAILABILITY_LOADING = 'REVIEW_AVAILABILITY_LOADING';
export const REVIEW_AVAILABILITY_SUCCESS = 'REVIEW_AVAILABILITY_SUCCESS';
export const REVIEW_AVAILABILITY_FAILED = 'REVIEW_AVAILABILITY_FAILED';

export const ADMIN_ROOMS_LOADING = 'ADMIN_ROOMS_LOADING';
export const ADMIN_ROOMS_SUCCESS = 'ADMIN_ROOMS_SUCCESS';
export const ADMIN_ROOMS_FAILED = 'ADMIN_ROOMS_FAILED';

export const CREATE_ROOM_LOADING = 'CREATE_ROOM_LOADING';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_ROOM_FAILED = 'CREATE_ROOM_FAILED';
export const CREATE_ROOM_RESET = 'CREATE_ROOM_RESET';

export const CLEAR_ERROR = 'CLEAR_ERROR';
