export const ALL_ROOMS_SUCCESS = 'ALL_ROOMS_SUCCESS';
export const ALL_ROOMS_FAILED = 'ALL_ROOMS_FAILED';

export const ROOM_DETAIL_SUCCESS = 'ROOM_DETAIL_SUCCESS';
export const ROOM_DETAIL_FAILED = 'ROOM_DETAIL_FAILED';

export const CLEAR_ERROR = 'CLEAR_ERROR';
