export const ALL_ROOMS_SUCCESS = 'ALL_ROOMS_SUCCESS';
export const ALL_ROOMS_FAILED = 'ALL_ROOMS_FAILED';

export const ROOM_DETAIL_SUCCESS = 'ROOM_DETAIL_SUCCESS';
export const ROOM_DETAIL_FAILED = 'ROOM_DETAIL_FAILED';

export const CREATE_REVIEW_LOADING = 'CREATE_REVIEW_LOADING';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_FAILED = 'CREATE_REVIEW_FAILED';
export const CREATE_REVIEW_RESET = 'CREATE_REVIEW_RESET';

export const CLEAR_ERROR = 'CLEAR_ERROR';
